#!/bin/bash
#
# 40autorandr: Change autorandr profile on thaw/resume

case "$1" in
    thaw|resume)
	/usr/local/bin/autorandr-update-display
	;;
    *)
        echo "Skipping $1 PM change..."
        ;;
esac
