#!/bin/bash
#
# 40autorandr: Change autorandr profile on thaw/resume

AUTORANDR="/usr/local/bin/autorandr"
XBACKLIGHT="/usr/bin/xbacklight"

find_user() {
    local D="$1"
    who | awk -vD="$D" '$5 ~ "\\(:"D"\\)$" {print $1}'
}

run_as_x_user() {
    local user="$1"; shift
    local cmd="$@"

    case "$user" in
	"")
	    ;;
	# Run as root:
	"(unknown)")
	    eval ${cmd}
	    ;;
	*)
	    /bin/su -c "$cmd" "$user"
	    ;;
    esac
}

update_backlight() {
    local user="$1"

    case $(detect_autorandr $user) in
	docked)
	    run_as_x_user $user $XBACKLIGHT -set 100%
	    ;;
	mobile)
	    run_as_x_user $user $XBACKLIGHT -set 70%
	    ;;
    esac
}

detect_autorandr() {
    local user="$1"
    run_as_x_user $user $AUTORANDR |gawk '/detected/ {print $1}'
}

update_display() {
    for X in /tmp/.X11-unix/X*; do
	D="${X##/tmp/.X11-unix/X}"

	user=$(find_user $D)
	export DISPLAY=":$D"

	run_as_x_user $user $AUTORANDR -c
	update_backlight $user
    done
}

case "$1" in
    thaw|resume)
	update_display
	;;
esac
